name: galaxy10-cli
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchmetrics
  - pytorch-cuda
  - pytorch-lightning
  - numpy
  - scikit-learn
  - h5py
  - tqdm
  - click
  - jupyter
  - pip
  - pip:
      - astronn
